libdav1d: invoke pip using python3

diff --git a/build-ffmpeg b/build-ffmpeg
--- a/build-ffmpeg
+++ b/build-ffmpeg
@@ -298,7 +298,10 @@ if ! command_exists "cargo"; then
 fi
 
 if ! command_exists "python"; then
-  echo "Python command not found. Lv2 filter and dav1d decoder will not be available."
+  echo "python command not found. Lv2 filter will not be available."
+fi
+if ! command_exists "python3"; then
+  echo "python3 command not found. dav1d decoder will not be available."
 fi
 
 ##
@@ -462,10 +465,10 @@ if build "cmake" "3.21.0"; then
   build_done "cmake" "3.21.0"
 fi
 
-if command_exists "python"; then
+if command_exists "python3"; then
   if build "dav1d" "0.9.2"; then
     # dav1d needs meson and ninja with nasm to be built
-    execute pip3 install meson ninja --quiet --no-cache-dir --disable-pip-version-check
+    execute python3 -m pip install meson ninja --quiet --no-cache-dir --disable-pip-version-check
     download "https://code.videolan.org/videolan/dav1d/-/archive/0.9.2/dav1d-0.9.2.tar.gz"
     make_dir build
     execute meson build --prefix="${WORKSPACE}" --buildtype=release --default-library=static --libdir="${WORKSPACE}"/lib
